export interface PermissionDefinition {
  key: string;
  group: string;
  description: string;
}

// This catalog seeds database records. Authorization resolves database data and never branches on roles.
export const initialPermissionCatalog: readonly PermissionDefinition[] = [
  { key: 'users.read', group: 'users', description: 'Ver usuarios' },
  { key: 'users.create', group: 'users', description: 'Crear usuarios' },
  { key: 'users.edit', group: 'users', description: 'Editar usuarios' },
  { key: 'users.disable', group: 'users', description: 'Desactivar usuarios' },
  { key: 'roles.read', group: 'users', description: 'Ver roles' },
  { key: 'roles.manage', group: 'users', description: 'Administrar roles' },
  { key: 'permissions.override', group: 'users', description: 'Administrar excepciones' },
  { key: 'sites.read', group: 'operations', description: 'Ver operaciones y zonas' },
  {
    key: 'sites.access_all',
    group: 'operations',
    description: 'Acceder a todas las operaciones y a la vista global',
  },
  { key: 'sites.manage', group: 'operations', description: 'Administrar operaciones' },
  { key: 'zones.manage', group: 'operations', description: 'Administrar zonas geográficas' },
  { key: 'customers.read', group: 'customers', description: 'Ver clientes' },
  { key: 'customers.create', group: 'customers', description: 'Crear clientes' },
  { key: 'customers.edit', group: 'customers', description: 'Editar clientes' },
  { key: 'customers.merge', group: 'customers', description: 'Fusionar clientes' },
  { key: 'customers.unmerge', group: 'customers', description: 'Revertir fusiones' },
  { key: 'customers.restrict', group: 'customers', description: 'Restringir clientes' },
  { key: 'customers.view_sensitive', group: 'customers', description: 'Ver datos sensibles' },
  { key: 'orders.read', group: 'orders', description: 'Ver pedidos' },
  { key: 'orders.create', group: 'orders', description: 'Crear pedidos' },
  { key: 'orders.edit', group: 'orders', description: 'Editar pedidos' },
  { key: 'orders.confirm', group: 'orders', description: 'Confirmar pedidos' },
  { key: 'orders.cancel', group: 'orders', description: 'Cancelar pedidos' },
  { key: 'orders.revert_status', group: 'orders', description: 'Revertir estados' },
  {
    key: 'orders.override_cycle_lock',
    group: 'orders',
    description: 'Modificar ciclos bloqueados',
  },
  { key: 'chat.use', group: 'chat', description: 'Usar el chat interno' },
  { key: 'chat.presence.read', group: 'chat', description: 'Ver la presencia de colegas' },
  {
    key: 'chat.share_reference',
    group: 'chat',
    description: 'Compartir referencias a pedidos o clientes en el chat',
  },
  { key: 'chat.links.manage', group: 'chat', description: 'Configurar quién habla con quién' },
  { key: 'messages.read', group: 'messaging', description: 'Ver mensajes' },
  { key: 'messages.send', group: 'messaging', description: 'Enviar mensajes' },
  { key: 'messages.templates.use', group: 'messaging', description: 'Usar plantillas' },
  { key: 'messages.templates.manage', group: 'messaging', description: 'Administrar plantillas' },
  { key: 'messaging.accounts.manage', group: 'messaging', description: 'Administrar cuentas' },
  { key: 'production.read', group: 'production', description: 'Ver producción' },
  { key: 'production.generate', group: 'production', description: 'Generar producción' },
  { key: 'menus.distribute', group: 'production', description: 'Distribuir menús por operación' },
  {
    key: 'menus.distribute_replace',
    group: 'production',
    description: 'Reemplazar personalizaciones regionales de menú',
  },
  { key: 'production.report', group: 'production', description: 'Informar producción real' },
  { key: 'production.adjust_surplus', group: 'production', description: 'Ajustar excedente' },
  { key: 'routes.read', group: 'delivery', description: 'Ver rutas' },
  { key: 'routes.manage', group: 'delivery', description: 'Administrar rutas' },
  { key: 'routes.publish', group: 'delivery', description: 'Publicar rutas' },
  { key: 'delivery.execute', group: 'delivery', description: 'Ejecutar reparto' },
  {
    key: 'delivery.trigger_messages',
    group: 'delivery',
    description: 'Disparar mensajes de reparto',
  },
  { key: 'payments.read', group: 'payments', description: 'Ver pagos' },
  { key: 'payments.record', group: 'payments', description: 'Registrar pagos' },
  { key: 'payments.settle', group: 'payments', description: 'Registrar rendiciones' },
  { key: 'payments.override', group: 'payments', description: 'Corregir pagos' },
  { key: 'cms.read', group: 'cms', description: 'Ver contenido' },
  { key: 'cms.edit', group: 'cms', description: 'Editar contenido' },
  { key: 'cms.publish', group: 'cms', description: 'Publicar contenido' },
  { key: 'ai.use', group: 'ai', description: 'Usar funciones de IA' },
  { key: 'ai.custom_instruction', group: 'ai', description: 'Usar instrucciones personalizadas' },
  { key: 'ai.prompts.manage', group: 'ai', description: 'Administrar prompts' },
  { key: 'ai.providers.manage', group: 'ai', description: 'Administrar proveedores de IA' },
  { key: 'ai.budgets.manage', group: 'ai', description: 'Administrar presupuestos de IA' },
  { key: 'ai.models.select', group: 'ai', description: 'Seleccionar modelos de IA' },
  { key: 'ai.images.generate', group: 'ai', description: 'Generar imágenes' },
  { key: 'audit.read', group: 'audit', description: 'Ver auditoría' },
  { key: 'audit.export', group: 'audit', description: 'Exportar auditoría' },
];
